[Paths]
media_dir = \\203.137.53.224\upload
#media_dir = D:\DbotManager\DbotManager\bin\Debug\python\upload
profile_dir = C:\Users\sound\Documents\GitHub\MT4\DbotManager\DbotManager\各種最新Src\python\profile

[WAIT_TIME]
min = 1.0
max = 3.0